export const LOGIN_USER_START = 'LOGIN_USER_START';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const LOGOUT = 'LOGOUT';


export const GET_PLANET_START = 'GET_PLANET_START';
export const GET_PLANET_SUCCESS = 'GET_PLANET_SUCCESS';
export const GET_PLANET_ERROR = 'GET_PLANET_ERROR';
export const CLEAR_PLANET_DATA = 'CLEAR_PLANET_DATA';

export const LOAD_MORE_START = 'LOAD_MORE_START';
export const LOAD_MORE_SUCCESS = 'LOAD_MORE_SUCCESS';
export const LOAD_MORE_ERROR = 'LOAD_MORE_ERROR';

export const STATUS = {
  LOADING: 'LOADING',
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
};